name: BuildRelease

# 指定此工作流的触发器
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # 匹配特定标签 (refs/tags)
    tags:
      - 'v*' # 推送事件匹配 v*, 例如 v1.0，v20.15.10 等来触发工作流
      
# 需要运行的作业组合
jobs:
  # 任务：创建 release 版本
  create-release:
    name: SwitchApp
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
          
    - name: 当前日期
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        # ${{ steps.date.outputs.date }}

    - name: 打包
      run: |
        # 查找删除.delme文件（用来实现GitHub空目录）
        find Files -type f -iname .delme -delete
        # 循环压缩Files目录下各app目录
        for file in Files/*
        do
        if [ -d "$file" ]
        then
          # echo "$file 是目录"
          cd $file
          zip -qr ../${file##*/}.zip *
          cd ../../
        elif [ -f "$file" ]
        then
          echo "$file 是文件"
        fi
        done
        # 将压缩文件移动到/Output目录
        mkdir -p Output && mv Files/*.zip Output
   
    - name: 发布
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        allowUpdates: true
        tag: ${{ steps.date.outputs.date }}
        prerelease: false
        artifacts: "Output/*.zip"

