name: BuildRelease

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: SwitchApp
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: 当前日期
      id: date
      run: |
        echo "date=$(date +'%YY%mm%dd')" >> $GITHUB_OUTPUT
        # ${{ steps.date.outputs.date }}
        
    - name: 发布
      uses: ncipollo/release-action@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ steps.date.outputs.date }}
        prerelease: false
        artifacts: "APPS/*.zip"

